### ISSUE TITLE
remote URL upload

### ISSUE THREAD

**Issue by c64bob** [ddurdle/PERL-CloudSync#1]
Hi,
great set of scripts, exactly what I am looking for! What do you think about this feature request: use the onedrive remote URL upload (https://dev.onedrive.com/items/upload_url.htm) to transfer the files directly from Google Drive to onedrive? One would have to share the file being transferred, use the public URL for the transfer to onedrive, then unshare the file again. This way a full sync should take significantly less time, and use up hardly any local bandwith.
Thanks

**Comment by ddurdle** [comment]
I actually implemented the routine uploadRemoteFile(URL,path,filename), but at the time I tested it, I found it very slow.  During my test, which involved using a YouTube URL, it took 30 mins to "remote upload" 350MB --> https://github.com/OneDrive/onedrive-api-docs/issues/63

**Comment by ddurdle** [comment]
Oh, and yes, your comment about the sharing from Google Drive to OneDrive would work.  If your item is a video, and you don't mind a transcoded copy, you could use a transcoded stream URL from Google Drive to feed into OneDrive.  Seems a bit of a security hole because you don't need to be logged in to retrieve the stream (so the stream or file doesn't need to be made public).

**Comment by ddurdle** [comment]
BTW, my strategy is that I load these scripts on various purchased VPS instances (purchased at around $10-$20/year).  One is unmetered but slow, the others are metered, but even at the cap of 4-5TB/month, I don't end up downloading+uploading that much data through this activity.  The OneDrive upload is much slower than Google's.

**Comment by c64bob** [comment]
I'm running a few tests in the onedrive API console, and find that the remote upload works reasonably well. Currently I'm uploading a 10GB test file and get around a few MB/s. 
The advantage of this approach is that it's asynchronous and parallel. So you could trigger a few hundred uploads and just wait until they are finished. Although one would have to keep track of the progress carefully...

**Comment by ddurdle** [comment]
Seems you can create and fetch the shareable links in Google Drive through the API -> http://stackoverflow.com/questions/11665215/is-it-possible-to-share-a-file-publicly-through-google-drive-api

It might be worth it to implement a routine to do this.

**Comment by c64bob** [comment]
That would be awesome!

**Comment by ddurdle** [comment]
Are you sure you can kick off multiples?  I did some testing today and when I kick off the first remote upload, the status of that job goes to inProgress, and subsequent requests with different URLs start off with a notStarted status.

**Comment by c64bob** [comment]
Yes, I'm positive. I submitted 10 remote uploads with a 10GB test file each. It took a while for the individual uploads to change into the inProgress state, but there were definitely several concurrently uploading. 
Do you still get slow speeds when using remote upload?

**Comment by ddurdle** [comment]
I submitted 2 1.5GB files for remote download at 1pm.  On a VPS, they take
about 30 seconds to download.

The first finished sometime around 4pm (3 hours).  The second didn't toggle
from notStarted to inProgress until the first has finished.  The second is
still in progress (was 1.35% complete at around 4pm).

**Comment by c64bob** [comment]
Sorry for hijacking this thread, but how exactly would I sync a specific folder from my google drive with my onedrive? I am already failing authenticating using OAuth and Google API 2.

**Comment by ddurdle** [comment]
Are you providing your own client ID and client secret or trying to use one I've setup?

**Comment by c64bob** [comment]
I am using my own ID and secret. 

Am 15. September 2015 22:03:24 MESZ, schrieb ddurdle <notifications@github.com>:

**Comment by ddurdle** [comment]
I made a change last night, it should be using the proper refresh and set token.

**Comment by c64bob** [comment]
Yes, that looks better! I can successfully authenticate with Google Drive and Onedrive now. However, I need to repeat this step for Onedrive every time I restart the console.pl. The Google Drive authorization is saved though.

**Comment by ddurdle** [comment]
I'll look at the onedrive.  Like the Google Drive and Amazon Cloud Drive, it should be saving the refresh and access tokens in a file such as od.name.db.  Can you confirm you see od.* files created.

**Comment by c64bob** [comment]
Yes, I can see the od.<myEmail>.db file.

**Comment by c64bob** [comment]
Additionally, when i try to sync folders after having logged in to both Google Drive and MS Onedrive, I get this error message:

> 1. XXX, *2*. YYY>sync folder Test 1 2
> folder = Test
> can't open od.YYY.sha1.db: No such file or directory at lib/dbm.pm line 58, <STDIN> line 3.

**Comment by ddurdle** [comment]
I just pushed out updates to handle these two issues.

For OneDrive, it wasn't saving the username inside the odb file -- fixed
For cases where the SHA file doesn't exist, it will create it instead of erroring out.

If you have files already saved on your OneDrive that may include files you are trying to sync from Google, I recommend you run "get changes".  That will populate the local hashes with information about what is stored on your OneDrive.  This way, when you perform a sync, it will avoid copying files already on your OneDrive.

Because OneDrive does not provide MD5 (only SHA1 and CRC32), I use "fisi" for syncing between Google Drive and OneDrive, which a MD5(filename+filesize).  For all other services (Amazon, Google Photo, Google Drive), I compare the real MD5 of the file to determine if a file needs to be synced.

**Comment by ddurdle** [comment]
P.S., I generally always run a "get changes" on all accounts I'm syncing into, to avoid trying to sync files already there.  On subsequent runs of "get changes", it will only retrieve new information (all changes since last ran).  So yes, it will be slow the first time you run it, but subsequent runs will only fetch "changes".

Remember that you can also load commands in a txt file and run perl console.pl -c commands.txt

Example....
load gd 1 durdle
load acd 2 ddurdle
get changes
sync folderid ##### 1 2

**Comment by c64bob** [comment]
Great, now the onedrive credentials are properly safed and reused.However, when running the sync folder command I am seeing this error:
Can't locate object method "getFolderIDByPath" via package "pDrive::oneDrive" at console.pl line 902, <STDIN> line 4.

**Comment by ddurdle** [comment]
You're syncing from onedrive to google drive?

**Comment by c64bob** [comment]
no, the other way around

**Comment by c64bob** [comment]
do you need more output for debugging?

**Comment by ddurdle** [comment]
No, I know what is wrong, but I didn't expect it to be an issue from Google Drive -> One Drive, only from One Drive -> Google Drive.

I added Amazon Cloud Drive support the other weekend and made a change on how folders are calculated.  I updated Google Drive but not One Drive, but I didn't think it mattered with pushing files to, only pulling files.

So, it is an easy fix, but I need about an hour to test.

**Comment by tonymorella** [comment]
I was able to get a link to gdrive and run "get download list" but when I run "get changes" or "download all" get this error:

Can't locate object method "getNextURL" via package "pDrive::gDrive" at ./console.pl line 596, <STDIN> line 10.

Also I figured this out by looking at the code, am I missing it or is there no other docs?

**Comment by ddurdle** [comment]
this issue with getFolderIDByPath is fixed.

**Comment by c64bob** [comment]
Yes it is. Thank you.
When I do a "sync folder Test 1 2" I get these responses:
...
DOWNLOAD Test T2 71d2c46af01f...
mkdir test path /tmp/pdrive//
URL =  ya29.AAKaE... /tmp/pdrive//30019
downloading /tmp/pdrive//30019...http://: Invalid host name.
success --> https://api.onedrive.com/v1.0/drive/root:/:/children?nameConflict=fail
...
Is this a significant error message about the invalid host name? And the "fail" part of the onedrive URL?

**Comment by c64bob** [comment]
Also, it keeps saying:
upload to service 1 
Shouldn't it sync from service 1 to service 2?

**Comment by ddurdle** [comment]
The counting on screen are off by 1 as it counts starting at 0.  I'll fix that so it is clear to the user.  So in this case, 1 is 2.

Is it successfully downloading the file?  There shouldn't be a http:// anywhere, to start with, as it should be all https

**Comment by ddurdle** [comment]
the nameConflict simply instructs OneDrive to fail with an error if you upload a file that already exists on OneDrive.  That part of their API doesn't seem to work as it simply overwrites the file instead of failing the action :)

**Comment by c64bob** [comment]
I see. That is a bit of a problem because it keeps doing a full sync of the folder I specify, even after a copy already exists on OneDrive. Shouldn't it skip the files already copied, or is there no way to keep track of them?

**Comment by ddurdle** [comment]
Did you run a "get changes" on the OneDrive account prior?  It should index
the changes and not reupload.

**Comment by c64bob** [comment]
Yes I did. It says:
changeID = XXXXXXXXXXXXXXXXXXXXXXX
success --> https://api.onedrive.com/v1.0/drive/root:/:/view.changes?select=%40content.downloadUrl%2Cname%2Cid%2Csize%2Cfile&token=XXXXXXXXXX

entries = 2
MD5: created = 0, skipped = 2
FISI: created = 0, skipped = 2
count = 2
next url

**Comment by ddurdle** [comment]
Here is a typical script (actually using right now) that copies a folder
(using folder ID in this case) from a Google Drive account to OneDrive,
Amazon and another Google Drive account.  After I load an account, I want
to make sure my local index is most up-to-date, so I run a "get changes" on
each account (except the source).  I'm often running multiple scripts at
all times, across different machines, so I don't rely on updating the local
index upon a file upload operation completion, but I use the change
tracking on the cloud services (so that it can capture all changes against
the account, and avoid uploading duplicates).

In this particular example, it will examine each file recursively under the
folder ID and crosscheck the file's MD5 against Amazon and Google Drive #2
and the MD5(fisi) against OneDrive.  It'll skip downloading the file
entirely if it is present on all of the services and download it and upload
it to the services missing the file.

commands file:

load gd 0 durdle
load gd 1 support
get changes
load acd 2 ddurdle
get changes
load od 3 ddurdle
get changes
sync folderid ########### 0 1 2 3

**Comment by ddurdle** [comment]
How many files did you sync?  It seems to only have seen 2 changes.  Although I was just running a sync and reran it afterwards (to validate all files synced, to which it finished successfully without resyncing any files), there is a chance OneDrive has changed something recently that is breaking the capture of changes.  The API is being highly developed, and a month back they introduced a change which broke the script's ability to read the changes, which I fixed.  I've haven't been syncing OneDrive for the past month as my "unlimited" account has been full (reach the 10TB allotment) and I had a battle trying to get them to give me more space.  4 months of back-and-forth and I only finally got a space increase yesterday (up to 50TB now, so 40TB free).  I'm back in action and have a lot of syncing to catch up on.

**Comment by c64bob** [comment]
I created a test folder containing two files, with which I am testing the sync functionality. So 2 changes should be right. So what does FISI skipped mean exactly? Didn't it use this to determine the sync status?

**Comment by c64bob** [comment]
I just copied two more files into my test folder, both are a bit larger in size. When I try the sync folder command, I get this error message:
upload to service 2 
file size for /tmp/pdrive//18076 is 163465939
Can't locate object method "CHUNKSIZE" via package "pDrive::Config" at lib/onedrive.pm line 309, <STDIN> line 4.

**Comment by c64bob** [comment]
By the way, how did you get Microsoft to increase the limit on your OneDrive? I am planning to backup my GDrive files on there, and will hit the 10TB mark easily...

**Comment by ddurdle** [comment]
Are you missing the chunksize in the config.cfg?
use constant CHUNKSIZE => (8*256*1024);

This seems the optimal value.

About 10 repeated requests made to onedrive@microsoft.com.  It was quite a nightmare.  Kept getting excuses why they couldn't update my account (we are not upgrading anyone else to unlimited at this time -- I'm already unlimited, contact us when you are out of space, you still have space, etc), but persistent paid off.  The key is to reiterate "I've been already granted unlimited" "I was told when I run out of my initial 10GB, to request more space" and "I'm out of space < 100MB".  When I finally got someone to comply, they told me it would take 2 weeks to get the space.  No email after that, but suddenly it was bumped up to 50TB from 10TB a week later.  Don't bother requesting the space increase until you are nearly empty -- you'll get denied with "you have more than 50GB free, contact us when you have less free".

**Comment by ddurdle** [comment]
sorry, the chunksize post removed the *s, it should be (8A256A1024), replace A with *, or simply 2097152

**Comment by c64bob** [comment]
Yes. Brilliant. I got it working now!
Thanks for your help. I'll give you feedback once I have successfully synced my 3TB GDrive folder.

**Comment by ddurdle** [comment]
I've added a mock version of the sync folder and sync folderid (invoked by mock sync folderid .... and mock sync folder ....) which will to a test-run without actually downloading or uploading anything.  It can be quickly used to determine what will happen in the real sync -- incase you feel something isn't right, and that it will try to re sync files already present.  You can turn the DEBUG in config.cfg to 1 in conjunction to get a log file that

**Comment by c64bob** [comment]
By the way, I have no luck getting the onedrive upgrade to unlimited so far. I did sign up for the beta in August, but they still haven't upgraded my account. Apparently there are too many who want unlimited at the moment, which is why the whole process takes that long, someone in the chat told me. Since I am only guaranteed 1TB anything else if voluntary on Microsoft's part.

How is your experience syncing with Amazon? Is that a better route to go for backing up my GDrive than Onedrive?

**Comment by ddurdle** [comment]
The chat people are useless.  Best way to get the upgrade is to email
onedrive@microsoft.com.  Tell them a) you were accepted for unlimited space
already (a lie for you, but they wont' check) b) you were told that when
you were running out of space to email this email address to get bumped c)
you have less than < 50GB space remaining, and mention the actual MB you
have free remaining -- be clear on how much free space you have left, you
want to reiterate that you are "out of space", in my case they only
listened to me when I had 109MB left.

The above email with all 3 mentions is what finally got them to make my
account have 50TB.

I still prefer Google Drive over all else.

Here's my pro/con:

Amazon Cloud Drive
PROS
- upload as fast as Google Drive
- truly unlimited (I'm up to 13TB)

CONS
- no transcoding support
- videos not playback through browser
- because no transcoding support, streaming some videos don't work (need to
pre-cace those videos)
- website is hard to manage files
- at some times, download speed has been slow, which introduces buffer
issues
- sharing folders with other users is limited (doesn't tie into your
account, only via link)

Microsoft One Drive:
PROS
- cheapest

CONS
- took > 4weeks to get bumped to 50TB
- slowest upload speed (5x slower than competition)
- uploads often run into issues and fail (need to resend entire file)
- transcoding is horrible quality and only works through browser (no KODI
support)

Google Drive
PROS
- upload speed is fast
- always fast download speeds
- truly unlimited (I'm up to 21TB)
- transcoded versions of video files available, so even 25+GB video files
playback smooth using transcoded version
- never had an issue with playback of any video except for contended
encoded in x265-helix

CONS
- most costly ($10/month)

**Comment by c64bob** [comment]
Thanks for that extensive reply! I will try my luck with onedrive, although clouddrive doesn't sound too bad either.
