### ISSUE TITLE
Node already exists 

### ISSUE THREAD

**Issue by c64bob** [ddurdle/PERL-CloudSync#7]
Hi there!

It seems there is a problem when syncing GDrive -> Amazon Cloud Drive. Even though I ran "get changes" before doing the sync, a lot of files are downloaded locally even though they already exist at the destination service. The corresponding messages are like this:
...
Saving to: ‘/tmp/pdrive//11329’
upload to service 2 
/tmp/pdrive//11329
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0  350M  100   281    0  192k    396   271k  0:22:03 --:--:--  0:22:03  271k
{"logref":"b8f69d79-ad8a-11e5-badf-331be3e65f4b","message":"Node with the name b9f0897e1da67ff80f114dcfc865f371 already exists under parentId vgpQ-iyQTi2YgfEryj73rA conflicting NodeId: _SgD8er3RseZ1YrM22amIA","code":"NAME_ALREADY_EXISTS","info":{"nodeId":"_SgD8Th8RxaR1YrM22amIA"}}DOWNLOAD MC f608e1c7cfc54aa22f30f68124c2841f f3997203fcbe61122870684917303df2

Any ideas?

**Comment by ddurdle** [comment]
The change tracking changed, debugging it now.

**Comment by ddurdle** [comment]
The tracking field are very dynamic and inconsistent.  I had updated this a few times last year.  I've revamped it and believe I have implemented one that will accommodate changes.  It's been pushed out to github.  Tested locally with some test cases, and passed.  I'm getting it with some exhaustive test cases right now (a few million tracking records) which will take a few hours to validate.  It might detect a few exceptional records that aren't working, so there might be a few additional fixes coming.

The implementation now in github should be working with 99% certainty. 

To "cleanup" and get back lost tracking history, you can run a "reset changeid".  Next time you run "get changes" it will fetch all changes and parse through and index any changes not tracked since it stopped working.

**Comment by c64bob** [comment]
Awesome, thank you!

**Comment by ddurdle** [comment]
Caution about resetting the change id.  The next get changes will run potentially a long time.  My testing I did today, my account generated a 40MB package containing tracking information.  That's 40MB of pure text.  It took a long time to parse through to construct the index.  Amazon doesn't break up the transmission like Google Drive or One Drive does.  Will keep looking at ways to optimize it or at least provide an indicator how long to process the change records.

On a positive note, my testing today had no failed cases where it failed to realize the file was already on the Amazon Cloud Drive service.
